theme: minima

collections:
  developers:
    output: true

defaults:
  - scope:
      path: ""
      type: "developers"
    values:
      layout: "developer"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
